
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - nodeexporter
      - cadvisor
      - alertmanager
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - --config.file=/etc/alertmanager/config.yml
    ports:
      - 9093:9093
    networks:
      - monitoring

  nodeexporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8080:8080
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - 9115:9115
    networks:
      - monitoring

networks:
  monitoring:
