
groups:
  - name: blackbox-alerts
    rules:
      - alert: GoogleDown
        expr: probe_success{job="blackbox_google"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Google est injoignable"
          description: "Blackbox n'a pas pu accéder à Google"

      - alert: SpringServiceDown
        expr: probe_success{job="blackbox_springboot"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service Spring Boot KO"
          description: "Blackbox ne peut pas joindre le endpoint actuator"
