groups:
  - name: blackbox-alerts
    rules:
      - alert: GoogleDown
        expr: probe_success{job="blackbox_google", instance="https://www.google.com"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Google est injoignable"
          description: "Blackbox n'a pas pu accéder à https://www.google.com"

      - alert: SpringServiceDown
        expr: probe_success{job="blackbox_springboot"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service Spring Boot KO"
          description: "Le endpoint /actuator/health n'est pas joignable"

