groups:
  - name: oracle_alerts
    rules:
      - alert: OracleExporterDown
        expr: up{job="oracle"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Oracle Exporter down"
          description: "L'exporter Oracle est inaccessible depuis 30 secondes."
