global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'oracle'
    static_configs:
      - targets: ['oracle_exporter:9161']
